### ISSUE TITLE
Differences in GDAL and Xarray Encoding of Zarr

### ISSUE THREAD

**Issue by christophenoel** [zarr-developers/geozarr-spec#12]
The discrepancies between GDAL and Xarray encoding of Zarr have been frequently noted, making it crucial to compile a comprehensive list of these differences. 

While I have not observed many contrasts in the encoding of coordinates and data, aside from the projection metadata attribute, it remains essential to document and comprehend these disparities. 

This will enable us to collaborate towards a shared understanding and possibly a harmonized approach.

**Comment by rabernat** [comment]
This is closely related to #7.

**Comment by christophenoel** [comment]
Maybe ? I have not noticed any difference between GDAL/xarray coordinates. I'm busy restoring all those Zarr from past project to confirm.
Have you seen any difference ?
