### ISSUE TITLE
GeoZarr Auxiliary Data (explicit attribute)

### ISSUE THREAD

**Issue by samsammurphy** [zarr-developers/geozarr-spec#16]
"[GeoZarr Auxiliary](https://github.com/zarr-developers/geozarr-spec/blob/main/geozarr-spec.md#geozarr-auxiliary-data) variable MUST include the attribute **_ARRAY_DIMENSIONS set as an empty array**"

I am wondering if we should be more explicit?.. something like..

_GeoZarr Auxiliary variable MUST include the attribute  **_IS_AUXILIARY set to True**_

**Comment by christophenoel** [comment]
This is (for now!) a pure mapping from the xarray conventions 

> Xarray’s terminology differs from the [CF terminology](https://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#terminology), where the “dimension coordinates” are called “coordinate variables”, and the “non-dimension coordinates” are called “auxiliary coordinate variables” (see [GH1295](https://github.com/pydata/xarray/issues/1295) for more details).

See more: https://github.com/pydata/xarray/issues/1295 

However, we might generalise this for any other class:

_GEOZARR_CLASS: data | coordinate | auxiliary | dataset

**Comment by dblodgett-usgs** [comment]
Over in #17 I misused `GeoZarr Auxiliary variable` assuming it was the name we were using for any variable that is merely a container for non-global for attributes, such as is used for a `grid_mapping`. What is the use case for `Auxiliary variables`? 

Maybe using an attribute that avoids the confusion or is more specific with regard to the purpose of the attribute would be helpful?
