### ISSUE TITLE
Relationship to GDAL multidimensional data model

### ISSUE THREAD

**Issue by ashiklom** [zarr-developers/geozarr-spec#27]
As of GDAL 3.1, GDAL has a [multidimensional raster data model](https://gdal.org/user/multidim_raster_data_model.html) and [API](https://gdal.org/api/index.html#multi-dimensional-array-api), albeit with what seems like a severely restricted feature set compared to most of GDAL. It apparently works well enough that it's been recommended as a way for users of the R `stars` library to read Zarr data (https://www.r-bloggers.com/2022/09/reading-zarr-files-with-r-package-stars/).

We should strive for compatibility with this in our implementation, and work with GDAL developers on any issues we identify.

**Comment by christophenoel** [comment]
Thanks you for reporting. 
Facilitating third-party library support is indeed a major point.
