### ISSUE TITLE
Per-chunk metadata (e.g., bbox)

### ISSUE THREAD

**Issue by benbovy** [zarr-developers/geozarr-spec#4]
@rabernat mentioned in https://twitter.com/rabernat/status/1617209410702696449 the idea of attaching a "GeoBox" (i.e., bbox + CRS + grid metadata) to a dataset, which is implemented in [odc-geo](https://github.com/opendatacube/odc-geo) and which is indeed useful for indexing.

Now I'm wondering if it would be possible to reconstruct such GeoBox for each chunk of a Zarr array or dataset? This would require storing a bbox per chunk. I'm not very familiar with Zarr specs, though. Is it possible/easy to store arbitrary metadata per chunk?

One potential use case would be scalable (e.g., dask-friendly) implementation of spatial regridding / resampling algorithms that would work with non-trivial datasets (e.g., curvilinear grids).

There is an interesting, somewhat related discussion in the geoarrow-specs repository: https://github.com/geoarrow/geoarrow/issues/19. As far as I understand, geospatial vector datasets are currently partitioned using multiple parquet files ([dask-geopandas parquet IO](https://dask-geopandas.readthedocs.io/en/stable/parquet.html), [dask-geopandas.read_parquet](https://dask-geopandas.readthedocs.io/en/stable/docs/reference/api/dask_geopandas.read_parquet.html#dask_geopandas.read_parquet)). For GeoZarr, however, we don't want one Zarr dataset per spatial partition I guess.

**Comment by benbovy** [comment]
It could also be defined at the [shard](https://zarr-specs.readthedocs.io/en/latest/extensions/storage-transformers/sharding/v1.0.html) level...

**Comment by benbovy** [comment]
I think that at this stage this is still a good place here (better in a new issue) for discussing if/how in general we can facilitate spatial indexing and/or partitioning of large datasets, even if this would require multiple zarr arrays (groups?) or any kind of zarr extension.

**Comment by TomAugspurger** [comment]
I might be missing something, but this should be possible today *without* need for per-chunk metadata. As long as you know have something like the [geotransform](https://gdal.org/user/raster_data_model.html#affine-geotransform) so that you know where the "origin" pixel is and the space between each pixel, and the size of each chunk, you should be able to get the bbox of each chunk with a bit of math.

This should be exactly the same has how GDAL / COG handle reading a single block out of a larger COG, just using multiple files / chunks.

Perhaps it isn't safe to assume that every chunk of this dataset is on the same grid / projection. But in that case, I'd recommend storing them in separate arrays.

**Comment by rabernat** [comment]
> As long as you know have something like the [geotransform](https://gdal.org/user/raster_data_model.html#affine-geotransform) so that you know where the "origin" pixel is and the space between each pixel, and the size of each chunk, you should be able to get the bbox of each chunk with a bit of math

This is interesting. 🤔  So the idea is that you would have an array stack with dimensions

```
image[item, y, x, band]
```

and then x coordinate variable like

```
x_origin[item]
y_origin[item]
```

Then you could construct the geotransform on the fly.

For the image collections we are talking about, it is safe to assume that the images all have the same `x` and `y` dimensions? Or could they possible be different sizes?

**Comment by joshmoore** [comment]
> [briannapagan](https://github.com/briannapagan) commented [2 days ago](https://github.com/zarr-developers/geozarr-spec/issues/4#issuecomment-1488512434)
Maybe can we have @joshmoore input here?

Sorry for the slow response. I don't any definitive responses but ...


> [rabernat](https://github.com/rabernat) commented [18 hours ago](https://github.com/zarr-developers/geozarr-spec/issues/4#issuecomment-1490903071)
> I want to close this as out of scope. Zarr does not allow per-chunk metadata. We are not making any Zarr extensions here. So therefore, we need to find a different solution to this use case.
 
Big :+1: for this strategy on this repo with the caveat that the individual convention efforts (GeoZarr, NGFF, etc) will likely identify things that to make it to `zarr-specs`.

> As long as you know have something like the [geotransform](https://gdal.org/user/raster_data_model.html#affine-geotransform) so that you know where the "origin" pixel

This reminds me somewhat of https://github.com/ome/ngff/pull/138 (which also triggered a discussion in NGFF space about use of cfconventions...)
