### ISSUE TITLE
Video for fast time series plotting is private

### ISSUE THREAD

**Issue by felixcremer** [zarr-developers/geozarr-spec#45]
This link: https://m.youtube.com/watch?v=Nt1URJqW71o&feature=youtu.be

Which is linked as fast time series plotting is indicated as private.

**Comment by briannapagan** [comment]
@christophenoel can you assist with this ?

**Comment by christophenoel** [comment]
@briannapagan @felixcremer : this should be fixed now.
Thanks

**Comment by felixcremer** [comment]
Yes, thank you
