### ISSUE TITLE
Diagramming geozarr dependencies for different ecosystems

### ISSUE THREAD

**Issue by briannapagan** [zarr-developers/geozarr-spec#6]
Following the excercise at the February 1st, 2023 GeoZarr SWG meeting (notes here) where we spent some quiet time listing use cases with the following prompt:
```As a [type of User], I need to [do something] with Zarr using [tool X]```

I am making an attempt of mapping these dependencies for the various use cases. This is the **python** dependency tree for opening a ****remote** zarr dataset** and doing some **basic plotting** i.e.:

```
store = 'https://ncsa.osn.xsede.org/Pangeo/pangeo-forge/pangeo-forge/CMIP6-PMIP-feedstock/CMIP6.PMIP.MIROC.MIROC-ES2L.past1000.r1i1p1f2.Amon.tas.gn.v20200318.zarr'
ds = xr.open_dataset(store, engine='zarr', chunks={}) 
ds['tas'].isel(time = 1000).plot(x='lon',y='lat',cmap='magma',vmin=0, vmax=50)
```

[xarray-zarr-plot-dependicies.pdf](https://github.com/zarr-developers/geozarr-spec/files/10744731/xarray-zarr-plot-dependicies.pdf)

Feedback/thoughts/other versions?

**Comment by rabernat** [comment]
Is this a duplicate of #5?

**Comment by briannapagan** [comment]
closed as duplicate.
